https://www.amazon.com/dp/B08GL65JKT:
  info:
    backing: Plastic
    brand: ABDL Shop
    capacity: 5000
    name: Carousel
    size: Large
    notes: 
    retailer: Amazon
    shipping: 0.00
    tapes: 2
    units: 10
    url: https://www.amazon.com/dp/B08GL65JKT
    waist_high: 44
    waist_low: 37
https://us.abuniverse.com/product/agz/:
  id: 356230
  info:
    backing: Cloth
    brand: ABU
    capacity: 7500
    name: AlphaGatorZ
    notes: 
    retailer: ABU
    shipping: 0.00
    tapes: 4
    url: https://us.abuniverse.com/product/agz/
  sizes:
    Large:
      waist_high: 42
      waist_low: 37
    Medium:
      waist_high: 36
      waist_low: 31
    XLarge:
      waist_high: 48
      waist_low: 43
https://bambinodiapers.com/products/x-plus-ultrastretch-all-white-diapers:
  info:
    backing: Plastic
    brand: Bambino
    capacity: 4500
    name: Bianco Ultra Stretch
    notes: 
    retailer: Bambino
    shipping: 0.00
    tapes: 4
    url: https://bambinodiapers.com/products/x-plus-ultrastretch-all-white-diapers
https://incontroldiapers.com/incontrol-premium-nights-briefs-with-whiff-x-technology/:
  info:
    backing: Plastic
    brand: InControl
    name: Premium Nights
    notes: 
    retailer: InControl
    shipping: 0.00
    tapes: 4
    url: https://incontroldiapers.com/incontrol-premium-nights-briefs-with-whiff-x-technology/
  sizes:
    Large:
      capacity: 5435
      waist_high: 42
      waist_low: 33
    Medium:
      capacity: 5217
      waist_high: 40
      waist_low: 30
    XLarge:
      capacity: 5455
      waist_high: 47
      waist_low: 36
https://www.littleforbig.com/wp-json/wc/store/products/155255:
  info:
    backing: Plastic
    brand: LittleForBig
    capacity: 5352
    name: Blushing Baby
    notes:
    retailer: LittleForBig
    shipping: 0.00
    tapes: 4
    url: https://www.littleforbig.com/product/blushing-baby-adult-diapers-10-pieces-packm-l/
  sizes:
    Large:
      waist_high: 46
      waist_low: 36
    Medium:
      waist_high: 38
      waist_low: 28
https://myinnerbaby.com/products/ageplay-outfitters-seaside-princess-printed-adult-diaper.json:
  info:
    backing: Plastic
    brand: MyInnerBaby
    capacity: 5000
    name: Seaside Princess
    notes: 
    retailer: MyInnerBaby
    shipping: 0.00
    tapes: 4
    url: https://myinnerbaby.com/products/ageplay-outfitters-seaside-princess-printed-adult-diaper
  sizes:
    Large:
      waist_high: 50
      waist_low: 36
    Medium:
      waist_high: 40
      waist_low: 32
https://www.northshorecare.com/adult-diapers/adult-diapers-with-tabs/northshore-megamax-tab-style-briefs/northshore-megamax-tab-style-briefs-medium-case40-410s:
  info:
    backing: Plastic
    brand: NorthShore
    capacity: 6500
    name: MEGAMAX
    notes:
    retailer: NorthShore
    shipping: 0.00
    tapes: 4
    url: https://www.northshorecare.com/adult-diapers/adult-diapers-with-tabs/northshore-megamax-tab-style-briefs/northshore-megamax-tab-style-briefs-medium-case40-410s